---
deployment:
  tasks:
    - /bin/echo "Deploying JukeBox from /home/appjbaic/repositories/jukebox-london"
    - cd /home/appjbaic/repositories/jukebox-london && npm ci --omit=dev
    - /bin/mkdir -p /home/appjbaic/repositories/jukebox-london/tmp
    - /usr/bin/touch /home/appjbaic/repositories/jukebox-london/tmp/restart.txt
