---
deployment:
  tasks:
    - export APP_DIR=/home/appjbaic/repositories/jukebox-london
    - /bin/echo "Deploying JukeBox from ${APP_DIR}"
    - cd "${APP_DIR}" && npm ci --omit=dev
    - /bin/mkdir -p "${APP_DIR}/tmp"
    - /usr/bin/touch "${APP_DIR}/tmp/restart.txt"
